name: Deploy link hub to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      force:
        description: "Run even if the last commit says [skip-index]"
        required: false
        default: "false"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # Run unless the last commit msg includes [skip-index], OR run if manually dispatched with force=true
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force == 'true' || (github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip-index]')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate site (docs/index.html)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python tools/repo_index.py
          ls -la docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    if: ${{ always() && needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
