name: Update repo link hub

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: repo-index-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate docs/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python tools/repo_index.py
          ls -la docs || true
          ls -la docs/index.html || true

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain -- docs/index.html)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/index.html
            git commit -m "ci: update docs/index.html"
            git push
          else
            echo "No changes to commit."
          fi
